import{RideController,STATES}from'./state-machine.js';import{click,alarm}from'../services/audio.js';import{applySettings}from'../core/settings.js';applySettings();
const q=s=>document.querySelector(s),controller=new RideController();let scene;const loader=q('#sim-loader');
async function initialiseScene(){try{const{RideScene}=await import('./scene.js');scene=new RideScene(q('#ride-canvas'))}catch(error){const fallback=q('#webgl-error');console.error('Ride scene initialisation failed:',error);fallback.dataset.error=error?.message||String(error);fallback.hidden=false;q('#load-status').textContent='3D unavailable — control simulation ready'}finally{setTimeout(()=>loader.classList.add('is-hidden'),450)}}initialiseScene();
const controls={power:q('#power'),gates:q('#gates'),restraints:q('#restraints'),platform:q('#platform'),drive:q('#drive')};controls.power.onclick=()=>controller.togglePower();controls.gates.onclick=()=>controller.toggleGates();controls.restraints.onclick=()=>controller.toggleRestraints();controls.platform.onclick=()=>controller.confirmPlatform();controls.drive.onclick=()=>controller.toggleDrive();q('#speed').onchange=e=>controller.setSpeed(e.target.value);q('#reset').onclick=()=>controller.resetFault();q('#estop').onclick=()=>{alarm();controller.emergencyStop()};
const dispatch=q('#dispatch');dispatch.addEventListener('pointerdown',e=>{e.currentTarget.setPointerCapture(e.pointerId);controller.beginDispatch()});dispatch.addEventListener('pointerup',()=>controller.endDispatch());dispatch.addEventListener('pointercancel',()=>controller.endDispatch());dispatch.addEventListener('keydown',e=>{if(!e.repeat&&(e.key===' '||e.key==='Enter'))controller.beginDispatch()});dispatch.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter')controller.endDispatch()});
for(const[id,key]of[['#arm-up','up'],['#arm-down','down'],['#rotate-left','left'],['#rotate-right','right']]){const el=q(id);const start=()=>{controller.hold(key,true);el.classList.add('pressed')};const end=()=>{controller.hold(key,false);el.classList.remove('pressed')};el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);start()});el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('keydown',e=>{if(!e.repeat&&(e.key===' '||e.key==='Enter'))start()});el.addEventListener('keyup',e=>{if(e.key===' '||e.key==='Enter')end()});el.addEventListener('blur',end)}
document.querySelectorAll('.view-tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.view-tabs button').forEach(x=>x.classList.remove('active'));b.classList.add('active');scene?.setCamera(b.dataset.camera)});document.addEventListener('click',e=>{if(e.target.closest('button'))click()});
function render(s,message,type){document.body.className=`sim-page state-${s.mode===STATES.RUNNING?'running':s.fault?'fault':'idle'}`;q('#state-label').lastChild.textContent=` ${s.mode}`;q('#score').textContent=s.score;const values={power:s.power,gates:s.gates,restraints:s.restraints,platform:s.platform,drive:s.drive&&!s.fault,fault:s.fault};Object.entries(values).forEach(([k,v])=>q(`[data-lamp="${k}"]`)?.classList.toggle('on',v));Object.entries(controls).forEach(([k,el])=>el.classList.toggle('active',s[k]));controls.gates.querySelector('small').textContent=s.gates?'CLOSED':'OPEN';controls.restraints.querySelector('small').textContent=s.restraints?'LOCKED':'UNLOCKED';controls.platform.querySelector('small').textContent=s.platform?'CLEAR':'NOT CLEAR';controls.drive.querySelector('small').textContent=s.drive?'ENABLED':'DISABLED';dispatch.classList.toggle('ready',controller.canDispatch);q('#estop').classList.toggle('latched',s.estop);if(message){q('#message-display p').textContent=message;toast(message,type)}}
function toast(message,type){const t=document.createElement('div');t.className=`toast ${type==='error'?'error':''}`;t.textContent=message;q('#toast-region').append(t);setTimeout(()=>t.remove(),3500)}controller.addEventListener('change',e=>render(e.detail.state,e.detail.message,e.detail.type));render(controller.state,'Turn control key to begin system startup.');
controller.addEventListener('tick',e=>{const s=e.detail;q('[data-telemetry="arm"]').textContent=s.arm.toFixed(1);q('[data-telemetry="rpm"]').textContent=Math.abs(s.rpm).toFixed(1);q('[data-telemetry="time"]').textContent=`${String(Math.floor(s.elapsed/60)).padStart(2,'0')}:${String(Math.floor(s.elapsed%60)).padStart(2,'0')}`});let previous=performance.now();function frame(now){const dt=Math.min(.05,(now-previous)/1000);previous=now;controller.tick(dt);scene?.update(controller.state,dt);requestAnimationFrame(frame)}requestAnimationFrame(frame);
setInterval(()=>q('#clock').textContent=new Date().toLocaleTimeString('en-GB'),1000);q('#help-button').onclick=()=>q('#help-dialog').showModal();q('#help-close').onclick=()=>q('#help-dialog').close();
