import*as THREE from'../../vendor/three/three.module.min.js';
export class RideScene{
 constructor(canvas){this.canvas=canvas;this.scene=new THREE.Scene();this.scene.background=new THREE.Color(0x111920);this.scene.fog=new THREE.Fog(0x111920,16,48);this.renderer=new THREE.WebGLRenderer({canvas,antialias:true,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,2));this.renderer.shadowMap.enabled=true;this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.camera=new THREE.PerspectiveCamera(48,1,.1,100);this.cameras={operator:[11,6,14],wide:[17,10,22],platform:[3,4,10]};this.camera.position.fromArray(this.cameras.operator);this.target=new THREE.Vector3(0,3,0);this.build();this.resize();new ResizeObserver(()=>this.resize()).observe(canvas.parentElement)}
 mat(color,metalness=.5,roughness=.55){return new THREE.MeshStandardMaterial({color,metalness,roughness})}
 mesh(geometry,material,parent=this.scene){const m=new THREE.Mesh(geometry,material);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m}
 build(){const hemi=new THREE.HemisphereLight(0x9db9c7,0x26301e,1.7);this.scene.add(hemi);const key=new THREE.DirectionalLight(0xfff1ce,3.2);key.position.set(7,15,9);key.castShadow=true;key.shadow.mapSize.set(2048,2048);this.scene.add(key);const acid=new THREE.PointLight(0xdfff00,20,18);acid.position.set(-5,5,-2);this.scene.add(acid);const ground=this.mesh(new THREE.PlaneGeometry(80,80),this.mat(0x151b1d,.05,.9));ground.rotation.x=-Math.PI/2;const grid=new THREE.GridHelper(80,40,0x364149,0x242c31);grid.position.y=.01;this.scene.add(grid);this.base=this.mesh(new THREE.CylinderGeometry(3.8,4.3,.7,32),this.mat(0x252e30,.8,.35));this.base.position.y=.35;this.armPivot=new THREE.Group();this.armPivot.position.y=1;this.scene.add(this.armPivot);const support=this.mesh(new THREE.BoxGeometry(1.5,7,1.6),this.mat(0x303a3c,.7,.3),this.armPivot);support.position.y=3.5;const cross=this.mesh(new THREE.BoxGeometry(11,.8,1.2),this.mat(0x3e4949,.75,.3),this.armPivot);cross.position.y=7;this.disc=new THREE.Group();this.disc.position.set(0,7,.7);this.armPivot.add(this.disc);const wheel=this.mesh(new THREE.CylinderGeometry(4.35,4.35,.6,48),this.mat(0x161c20,.8,.28),this.disc);wheel.rotation.x=Math.PI/2;const ring=this.mesh(new THREE.TorusGeometry(3.75,.3,10,48),this.mat(0xdfff00,.3,.32),this.disc);for(let i=0;i<16;i++){const a=i/16*Math.PI*2,seat=this.mesh(new THREE.BoxGeometry(.65,.55,.65),this.mat(0x343e43,.65,.35),this.disc);seat.position.set(Math.cos(a)*3.75,Math.sin(a)*3.75,0);seat.rotation.z=a}for(const x of[-5.7,5.7]){const tower=this.mesh(new THREE.BoxGeometry(1.1,8,1.5),this.mat(0x252e33,.8,.3));tower.position.set(x,4,0);const brace=this.mesh(new THREE.BoxGeometry(.35,10,.35),this.mat(0x485252,.8,.3));brace.position.set(x,3.4,0);brace.rotation.z=x>0?-.65:.65}const fenceMat=this.mat(0x394347,.7,.45);for(let x=-9;x<=9;x+=2){const p=this.mesh(new THREE.BoxGeometry(.08,1.4,.08),fenceMat);p.position.set(x,.7,6)}const rail=this.mesh(new THREE.BoxGeometry(18,.08,.08),fenceMat);rail.position.set(0,1.25,6)}
 resize(){const p=this.canvas.parentElement,w=p.clientWidth,h=p.clientHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix()}
 setCamera(name){const p=this.cameras[name]||this.cameras.operator;this.camera.position.fromArray(p)}
 update(state,dt){this.armPivot.rotation.z=THREE.MathUtils.lerp(this.armPivot.rotation.z,-THREE.MathUtils.degToRad(state.arm),Math.min(1,dt*3));this.disc.rotation.z+=state.rpm*Math.PI*2/60*dt;this.camera.lookAt(this.target);this.renderer.render(this.scene,this.camera)}
}
