export const STATES={COLD:'COLD & SAFE',READY:'READY TO DISPATCH',RUNNING:'CYCLE RUNNING',FAULT:'FAULT LATCHED',COMPLETE:'CYCLE COMPLETE'};
export class RideController extends EventTarget{
 constructor(){super();this.state={mode:STATES.COLD,power:false,gates:false,restraints:false,platform:false,drive:false,estop:false,fault:false,arm:0,rpm:0,direction:0,speed:2,elapsed:0,score:100,cycles:0};this.holds=new Set();this.dispatchStarted=0}
 emit(message,type='info'){this.dispatchEvent(new CustomEvent('change',{detail:{state:{...this.state},message,type}}))}
 get interlocks(){const s=this.state;return{power:s.power,gates:s.gates,restraints:s.restraints,platform:s.platform,drive:s.drive&&!s.fault&&!s.estop}}
 get canDispatch(){return Object.values(this.interlocks).every(Boolean)&&this.state.mode!==STATES.RUNNING}
 reject(message){this.state.score=Math.max(0,this.state.score-2);this.emit(message,'error')}
 togglePower(){if(this.state.mode===STATES.RUNNING)return this.reject('Control power cannot be isolated during a cycle.');this.state.power=!this.state.power;if(!this.state.power)Object.assign(this.state,{drive:false,platform:false,mode:STATES.COLD});else this.updateReady();this.emit(this.state.power?'Control circuits energised. Complete platform procedure.':'Control power isolated.')}
 toggleGates(){if(!this.state.power)return this.reject('Control power is required.');if(this.state.mode===STATES.RUNNING)return this.reject('Gate circuit is locked during motion.');if(this.state.restraints&&this.state.gates)return this.reject('Unlock restraints before opening gates.');this.state.gates=!this.state.gates;this.state.platform=false;this.updateReady();this.emit(this.state.gates?'Platform gates closed.':'Platform gates opened; clear confirmation removed.')}
 toggleRestraints(){if(!this.state.gates)return this.reject('Close platform gates before operating restraints.');if(this.state.mode===STATES.RUNNING)return this.reject('Restraint circuit is locked during motion.');this.state.restraints=!this.state.restraints;this.state.platform=false;this.updateReady();this.emit(this.state.restraints?'Restraints locked. Visually verify every row.':'Restraints released.')}
 confirmPlatform(){if(!this.state.gates||!this.state.restraints)return this.reject('Gates and restraints must prove before platform clearance.');if(this.state.mode===STATES.RUNNING)return;this.state.platform=!this.state.platform;this.updateReady();this.emit(this.state.platform?'Platform clear confirmed by operator.':'Platform clear confirmation cancelled.')}
 toggleDrive(){if(!this.state.power)return this.reject('Control power is required.');if(this.state.mode===STATES.RUNNING)return this.reject('Drive enable cannot change while running.');this.state.drive=!this.state.drive;this.updateReady();this.emit(this.state.drive?'Main drive enabled.':'Main drive disabled.')}
 setSpeed(value){if(this.state.mode===STATES.RUNNING)return this.reject('Speed set is locked during a cycle.');this.state.speed=Number(value);this.emit(`Speed programme ${value} selected.`)}
 updateReady(){if(this.canDispatch)this.state.mode=STATES.READY;else if(!this.state.fault)this.state.mode=STATES.COLD}
 beginDispatch(){if(!this.canDispatch)return this.reject('Dispatch denied: one or more safety circuits are open.');this.dispatchStarted=performance.now();this.emit('Dispatch validation started. Continue holding.')}
 endDispatch(){if(!this.dispatchStarted)return;const held=performance.now()-this.dispatchStarted;this.dispatchStarted=0;if(held<850)return this.reject('Dispatch button released too early.');if(this.canDispatch){this.state.mode=STATES.RUNNING;this.state.elapsed=0;this.emit('Cycle dispatched. Manual controls enabled.') }else this.reject('Dispatch interrupted by an open interlock.')}
 emergencyStop(){if(!this.state.estop){this.state.estop=true;this.state.fault=true;this.state.mode=STATES.FAULT;this.state.drive=false;this.holds.clear();this.emit('EMERGENCY STOP LATCHED — motion braking active.','error')}else{this.state.estop=false;this.emit('Emergency stop released. Press fault reset to acknowledge.')}}
 resetFault(){if(this.state.estop)return this.reject('Release the emergency stop before reset.');if(Math.abs(this.state.rpm)>.2)return this.reject('Reset denied while disc is moving.');this.state.fault=false;this.updateReady();this.emit('Fault circuit reset. Re-establish drive enable.')}
 hold(control,on){if(this.state.mode!==STATES.RUNNING&&on)return this.reject('Manual motion controls require an active cycle.');on?this.holds.add(control):this.holds.delete(control)}
 tick(dt){const s=this.state,maxRpm=[0,5.5,8.5,12][s.speed],armRate=17;if(s.mode===STATES.RUNNING&&!s.fault){s.elapsed+=dt;if(this.holds.has('up'))s.arm=Math.min(165,s.arm+armRate*dt);if(this.holds.has('down'))s.arm=Math.max(0,s.arm-armRate*dt);let target=0;if(this.holds.has('left'))target=-maxRpm;if(this.holds.has('right'))target=maxRpm;s.rpm+=(target-s.rpm)*Math.min(1,dt*1.8);if(s.elapsed>150){s.rpm*=Math.max(0,1-dt*2);s.arm=Math.max(0,s.arm-armRate*dt);if(s.arm===0&&Math.abs(s.rpm)<.15){s.rpm=0;s.mode=STATES.COMPLETE;s.drive=false;s.cycles++;this.emit('Cycle complete. Unlock restraints, then open platform gates.')}}}else{s.rpm*=Math.max(0,1-dt*2.5);if(s.fault)s.arm=Math.max(0,s.arm-armRate*.25*dt)}this.dispatchEvent(new CustomEvent('tick',{detail:{...s}}))}
}
